//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShelf
    {
        public int Id { get; set; }
        public string ShelfNumber { get; set; }
        public int Capacity { get; set; }
        public int UsedCapacity { get; set; }
        public int AvailableCapacity { get; set; }
    }
}
