//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Books
    {
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string Writer { get; set; }
        public int Count { get; set; }
        public int InShelfCount { get; set; }
        public int OutShelfCount { get; set; }
        public int ShelfId { get; set; }
        public int Expr1 { get; set; }
    }
}
